### ISSUE TITLE
Handling of null values mapped to optional URL property

### ISSUE THREAD

**Issue by jpstuehler** [lyft/mapper#105]
I'm mapping this JSON object:
```
{
      "id": 19627,
      "name": "Viktor Bestayev",
      "credits": "Cinematography",
      "image_url": null
}
```
to this model
```
struct Cast: Mappable {
    let castId: Int
    let name: String
    let credits: String
    let imageURL: URL?
    
    init(map: Mapper) throws {
        try castId = map.from("id")
        try name = map.from("name")
        try credits = map.from("credits")
        imageURL = map.optionalFrom("image_url")
    }
}
```

And this throws an _MapperError.convertibleError_ because of the image_url null value. What is the intended way of handling this case?

**Comment by keith** [comment]
Ah yes. I knew this would come up eventually. That's a good question. Currently we sidestep this since our API does not send any null values, the keys are just omitted from the response. In the meantime, assuming you need to solve this now, I would create a small transformation function that handles the null value.

I'll think more about how we may solve this on a higher level.

**Comment by gumnym** [comment]
In my case this is happening also if comment part of code reponsible for mapping variable that have null value in json

**Comment by keith** [comment]
So looking back at this issue now, this behavior is actually correct right? In your email the `image_url` is null, so you end up getting `nil` from that URL correct? Were you expecting something else?

**Comment by keith** [comment]
@gumnym can you provide a project / playground / snippet with your example issue?

**Comment by gumnym** [comment]
Xcode 8.3.3
ModelMapper (6.0.0)
Moya (8.0.5)
Moya-ModelMapper (4.1.1)
RxSwift (3.6.1)

mapObject throws error "jsonMapping(Status Code: 200, Data Length: 296)" it looks like struct initializer is not getting called.


```swift
import Mapper

struct User: Mappable {
    let birth: String
    let id: String
    let photo: String?
    let email: String
    let token: String
    let gender: String

    init (map: Mapper) throws {
        
        try birth = map.from("birth")
        try id = map.from("id")
        photo = map.optionalFrom("photo")
        try email = map.from("email")
        try token = map.from("token")
        try gender = map.from("gender")
    }
}
```

```swift
func registerRequest(email: String, password: String, birthTimeStamp: UInt, isMale: Bool) -> Observable<User> {
        return provider!.request(.signUp(email: email, password: password, birthTimeStamp: birthTimeStamp, isMale: isMale)).filterSuccessfulStatusCodes().mapObject(type:User.self)
    }
```

Example Json:

```json
{
	"id": "D46A4CE2-BD5C-C77F-FF39-AF62292BF200",
	"birth": "527644800000",
	"gender": "male",
	"photo": null,
	"photo_width": "0",
	"photo_height": "0",
	"email": "atesta10029@gmail.com",
	"name": "atesta10029@gmail.com",
	"token": "88E7D4C1-B08B-0B76-FFA7-395627AC8000"
}
```

**Comment by keith** [comment]
Looks like that is a step before `Mapper`, that must be happening in `Moya-ModelMapper`, if the initializer isn't called, it must be failing there.

**Comment by gumnym** [comment]
But where it could be, if I use mapJSON() instead of mapObject(type:User.self) then it returns me valid JSON

**Comment by keith** [comment]
I'm not sure what `mapJSON()` is either? Is that part of `Moya-ModelMapper` as well? It might be worth opening an issue over there if your `Mappable` implementation works when you use it directly

**Comment by realcarlos** [comment]
Hi I met the same problem ,any solutions?

**Comment by yveslym** [comment]
it might be a late answer but there's an optional method to handle the nil value that i used in my project 

` url = map.optionalFrom("url") // Optional property`

you can still find the documentation [here](https://github.com/sunshinejr/Moya-ModelMapper)

**Comment by keith** [comment]
If I add this example to the Mapper tests, it passes as expected:

```swift
func testExample() throws {
    struct User: Mappable {
        let birth: String
        let id: String
        let photo: String?
        let email: String
        let token: String
        let gender: String

        init (map: Mapper) throws {
            try birth = map.from("birth")
            try id = map.from("id")
            photo = map.optionalFrom("photo")
            try email = map.from("email")
            try token = map.from("token")
            try gender = map.from("gender")
        }
    }

    let dictionary: NSDictionary = [
        "id": "D46A4CE2-BD5C-C77F-FF39-AF62292BF200",
        "birth": "527644800000",
        "gender": "male",
        "photo": NSNull(),
        "photo_width": "0",
        "photo_height": "0",
        "email": "atesta10029@gmail.com",
        "name": "atesta10029@gmail.com",
        "token": "88E7D4C1-B08B-0B76-FFA7-395627AC8000"

    ]

    let user = try User.init(map: Mapper(JSON: dictionary))
    XCTAssertNil(user.photo)
    XCTAssertEqual(user.id, "D46A4CE2-BD5C-C77F-FF39-AF62292BF200")
}
```

If you're still having issues with this, I believe it's with Moya-ModelMapper. Feel free to open a new issue if you find that it's part of Mapper
