### ISSUE TITLE
Converting JSON array that has multiple object types

### ISSUE THREAD

**Issue by ivanmkc** [lyft/mapper#111]
Hi, 

I have a JSON array that contains two types of objects (e.g. TypeA and TypeB), both of which correspond to Swift structs that conform to the same protocol 'CommonInfo'.
I know the type of each JSON object by a 'type' property on each object. How can I map this JSON array to a Swift array of type [CommonInfo] ?

Thanks!

**Comment by keith** [comment]
We have a similar case of this where we have different payment accounts (such as credit card vs apple pay), and they share a similar base protocol.

The way we accomplish this is by something like this:

```swift
func chargeAccount(from dictionary: NSDictionary) -> ChargeAccount? {
    guard let type = dictionary["type"] as? String, let method = ChargeAccountType(rawValue: type) else {
        return nil
    }

    switch method {
    case .applePay:
        return ApplePay.from(dictionary)
    ...
    }
}

let response: [NSDictionary] = ...
let chargeAccounts: [ChargeAccount] = response.flatMap(createChargeAccount) ?? []
```

Here you can see that we handle each dictionary individually, and switch based on the `type` key, then in the switch statement we call the individual Mapper initializer for each separate type.

Let me know if you have any other questions!

**Comment by ivanmkc** [comment]
Thanks! I'll give it a try today or tomorrow.

**Comment by ivanmkc** [comment]
Hm, this won't work as I am using Moya with uses type inference to convert the JSON to a specific type:


`
provider
            .request(targetType)
            .mapArray(type: T.self)
`

The question is, how do I get T to represent both TypeA and TypeB and call the respective constructors?

**Comment by keith** [comment]
I guess then you need `T` to be something that inherits from your custom protocol, and also from `Mappable`.

**Comment by ivanmkc** [comment]
Thanks, they do but there is nowhere to put the logic on how to different the two types.
I ended up downloading every as a JSON array and manually calling the correct init function for each JSON element in the array.

**Comment by keith** [comment]
Sounds good. You might consider adding something to the Moya wrapper for this.
