### ISSUE TITLE
Map root array into Models

### ISSUE THREAD

**Issue by Crityk** [lyft/mapper#119]
Hi,
 I need to parse root array of objects into Models. I have declared my model and was hoping to get it working like this 
[Section].from(response) where response is array and excpted result should be array of Section not only Section itself. Please let me know how to do it in Mapper.

Thanks

**Comment by keith** [comment]
Yep this is possible with Mapper. But instead of the syntax you're showing above you do this:

```swift
let jsonArray: NSArray = ...
let sections = Section.from(jsonArray) // Here sections is a [Section]
```

**Comment by Crityk** [comment]
oh thanks alot Keith. I passed an array but was not casting it so it was giving errors. let me check output.
