### ISSUE TITLE
Issues when using firebase

### ISSUE THREAD

**Issue by smalam119** [lyft/mapper#122]
I am using Swift 3 (may not upgrade to 4 for some reason) and ModelMapper 6.0.0. Everything was going fine until I try to add firebase. After adding firebase model mapper is throwing some error. e.g.
/Users/sayedmahmudulalam/insuree_user/Pods/ModelMapper/Sources/NSURL+Convertible.swift:13:24: Invalid redeclaration of 'fromMap'
/Users/sayedmahmudulalam/insuree_user/Pods/ModelMapper/Sources/URL+Convertible.swift:4:16: Redundant conformance of 'URL' to protocol 'Convertible'
/Users/sayedmahmudulalam/insuree_user/Pods/ModelMapper/Sources/URL+Convertible.swift:13:24: Invalid redeclaration of 'fromMap'

Can you please explain the reason or suggest some alternate version?

**Comment by keith** [comment]
It looks like you upgraded Mapper after we moved `NSURL+Convertible.swift` to `URL+Convertible.swift` but yet you still have both files. You can remove the former and it should resolve this conflict.

**Comment by smalam119** [comment]
Thanks a lot. I will do it and come back to you.

**Comment by smalam119** [comment]
I have updated ModelMapper to 7.2.0. Then there is a issue in NSDIctionary + Safety.swift. It couldn't find the 'split' function of the String class. So, I have commented out for the time being. Now everything works well. Thank you.
