### ISSUE TITLE
Realm with Mapper

### ISSUE THREAD

**Issue by amirpervaiz086** [lyft/mapper#123]
Hi,
 I am trying to use Mappable with Realms object. Previously, I had struct and it was subclassed from the Mappable and I implemented init function. For Realm, I converted my struct to class and conform Object protocol. Now issue is, our model contains optional Int? but in Realm Optional Int can be defined by 'RealmOptional; but when change type, I start getting errors in Mapper init function since that type is unknown to the compiler. Can you please send me any example how to use it with Mapper?

Thanks,
Amir

**Comment by amirpervaiz086** [comment]
anyone guys? @mleventi

**Comment by amirpervaiz086** [comment]
@keith

**Comment by keith** [comment]
It sounds like you'll need to create a custom transformation function, or make RealmOptional conform to Convertible to make this work. Can you post an abridge example of your class and struct?

**Comment by astha-gupta** [comment]
Hey Amir - Can you give an example of how you implemented Lyft mapper with Realm?

**Comment by keith** [comment]
Feel free to submit a new issue if this is still a problem!
