### ISSUE TITLE
Suggestion: Deserialization can handle wrong format in JSON

### ISSUE THREAD

**Issue by sadiq81** [lyft/mapper#130]
This is a suggestion to allow mapper to handle the case that sometimes the types from the server does not types we expect.

Fx sometimes we expect a double but the server sends a double as string.

This could be done by removing the extensions in "DefaultConvertible" and instead implement Extensions for numbers that conform to Convertible

fx

```
import Foundation
import Mapper

extension Double: Convertible {
    /// Create a Double from Mapper
    ///
    /// - parameter value: The object (or nil) passed from Mapper
    ///
    /// - throws: MapperError.convertibleError if the passed value is not a String
    /// - throws: MapperError.customError      if the passed value is a String but the Double initializer fails
    ///
    /// - returns: The created double
    public static func fromMap(_ value: Any) throws -> Double {

        if let double = value as? Double {
            return double
        }

        guard let string = value as? String else {
            throw MapperError.convertibleError(value: value, type: String.self)
        }

        guard let double = Double(string) else {
            throw MapperError.customError(field: nil, message: "'\(string)' is not a valid Double")
        }

        return double
    }
}
```
 
Also another suggestion could be that mapper does not care if variables are lowercase/uppercase or if  camelcase is used but underscore naming is used.

**Comment by keith** [comment]
This has been suggested a few times, here is our current thinking on this https://github.com/lyft/mapper/pull/114#issuecomment-334662908

**Comment by keith** [comment]
Feel free to submit another issue if you have other thoughts about this!
