### ISSUE TITLE
Array within array parsing

### ISSUE THREAD

**Issue by amitm7** [lyft/mapper#139]
"exclusions" : [
    [
      {
        "facility_id" : "1",
        "options_id" : "4"
      },
      {
        "facility_id" : "2",
        "options_id" : "6"
      }
    ],
    [
      {
        "facility_id" : "1",
        "options_id" : "3"
      },
      {
        "facility_id" : "3",
        "options_id" : "12"
      }
    ],
    [
      {
        "facility_id" : "2",
        "options_id" : "7"
      },
      {
        "facility_id" : "3",
        "options_id" : "12"
      }
    ]
  ]

**Comment by amitm7** [comment]
Can someone Please help how to write the mapper for JSON above

**Comment by amitm7** [comment]
able to fix .. closig

**Comment by anilkumar416** [comment]
Hi can you share pojo

**Comment by keith** [comment]
Likely what toy should do in this case is create a second type to represent the nested objects and then decode [ThatType] on your parent type
