### ISSUE TITLE
Argument labels do not match

### ISSUE THREAD

**Issue by aabanaag** [lyft/mapper#151]
I'm using SwiftyJSON with Alamofire and trying to incorporate Mapper within the mix but I'm getting this.

![image](https://user-images.githubusercontent.com/2245822/45439269-e9bf5380-b6eb-11e8-97a8-c7b78f02b15d.png)

**Comment by keith** [comment]
The `from` function takes a `NSDictionary` or a `NSArray` https://github.com/lyft/mapper/blob/8b49f0d825b2df3dfda5fc82174aa605ac1c4465/Sources/Mappable.swift, it looks like you're passing a `JSON` type defined elsewhere. You can add an extension to `Mappable` to accept that, or you need to pass a compatible type.

**Comment by aabanaag** [comment]
the JSON type came from SwiftyJSON.

**Comment by keith** [comment]
Yep, so you'll need to get a Mapper compatible type from it
