### ISSUE TITLE
Is this still good approach since Swift now has Decodable?

### ISSUE THREAD

**Issue by rlam3** [lyft/mapper#154]
Is this still good approach since Swift now has Decodable?
https://stackoverflow.com/questions/24410881/reading-in-a-json-file-using-swift

**Comment by keith** [comment]
This is kind of up to you. We're still happily using Mapper and have no plans to move away from it.

Codable also has some different trade-offs for more complex cases. For example if your property names don't match your JSON names, with Codable you have to define an enum with the mappings. This enum is outside of your initializer, so you have to cross reference that to understand what keys are being decoded. Also with Codable you have to duplicate type information for custom initializers, where with Mapper you get that inference.

The biggest advantage of Codable IMO is that it's part of the language.
