### ISSUE TITLE
Map object with inheritance

### ISSUE THREAD

**Issue by paulosaure** [lyft/mapper#166]
Hello,

I have the following code :

```
class Farm: Mappable {
    var animals: [Animal] = []
}
```
```
class Animal: Mappable {
    // enum type (ex ."dog", "cat" ...)
}
```
```
class Dog: Mappable {
}
```

```
class Cat: Mappable {
}
```

My WebService return a list with different animals (for my Farm model). 
I would like to parse (and cast parsed object) using an attribute "type" in the response of WS.
I think, I can do this with **Custom Transformations** but is it a better method ?

**Comment by keith** [comment]
Yea for our similar cases we always used custom transformation functions that extracted the `type` and did a `switch` and deserialized the correct types that way
