### ISSUE TITLE
Have consider porting you bug report to Swift bug report ?

### ISSUE THREAD

**Issue by mackoj** [lyft/mapper#21]
Hi,

Since Swift is open source now we have access to a more open bug tracking tool.

https://bugs.swift.org/secure/Dashboard.jspa

Have you consider porting your radar to this plateform ?

**Comment by keith** [comment]
I have thought about doing this. I've been meaning to make a mailing list post asking if that's what we should do. Since if the swift team is actually reading radars still I don't want to add a bunch of duplicate issues. I'll try to send that out soon.

**Comment by keith** [comment]
Sounds like the swift core team would like this https://lists.swift.org/pipermail/swift-dev/Week-of-Mon-20151228/000622.html

**Comment by mackoj** [comment]
Great I hope this way these issues get fix faster...

**Comment by keith** [comment]
If you'd like to help copy any of these over it would be greatly appreciated. Each open radar link has a comment with a link to any relevant project/playground files.

**Comment by keith** [comment]
I never really got around to this. I think most of these radars are out of date now though. Once Swift 3.0 is shipped we'll have to revisit any issues we saw before.

Closing this!
