### ISSUE TITLE
Carthage fails to build Mapper for watchOS

### ISSUE THREAD

**Issue by Austinate** [lyft/mapper#25]
This line
`carthage update --platform watchos` 
Gives such output:
```
*** Fetching mapper
*** Checking out mapper at "1.0.1"
*** xcodebuild output can be found in /var/folders/f_/t413twvd70969xm53wbmq4j00000gn/T/carthage-xcodebuild.beMwhr.log
*** Skipped building mapper due to the error:
Dependency "mapper" has no shared framework schemes for any of the platforms: watchOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Lyft/mapper/issues/new
```

Adding `--no-skip-current` and/or removing `--platform watchOS` doesn't help

I'll try to check what's happening.

**Comment by keith** [comment]
Does adding an explicit deployment target, as you did for tvOS, fix this?

**Comment by Austinate** [comment]
Unfortunately, nope :disappointed:

**Comment by keith** [comment]
So this is when you actually have a project with a watchOS target and you try to integrate with carthage? Which version of carthage are you using? I've been testing on 0.11.0

**Comment by Austinate** [comment]
Yes, i've created project with watchOS 2.0 target (of with iOS-one & default unit & ui tests). 
Carthage has same 0.11 version

**Comment by keith** [comment]
Let me dig in to this too. This must have something to do with the universal framework.

**Comment by dmauro** [comment]
Also seeing this with tvOS fwiw

**Comment by keith** [comment]
Ah! Could this be because I haven't tagged the release since we've added support for these? I believe it is. I've been putting that off for no reason, let me do that now.

**Comment by keith** [comment]
Pushed 1.0.2 to fix this. Everything should be good now, when updating with carthage just make sure it downloads that version. I've tested this locally and it looks good. Reopen this if you find any more issues! Thanks!

**Comment by Austinate** [comment]
Builds fine! :+1: not sure how could i miss why this issue was happening  (╯°□°）╯︵ ┻━┻
