### ISSUE TITLE
Mark App extension safe API only

### ISSUE THREAD

**Issue by dmauro** [lyft/mapper#28]
It looks like this isn't using anything that's not extension safe, but it's not marked as safe. Could we get it marked as safe so I can get rid of this warning? :)

**Comment by keith** [comment]
Oops! Definitely. Feel free to submit a PR if you can beat me to it. Otherwise I'll get it in shortly.

**Comment by keith** [comment]
How are you including Mapper in your project? Just so I can reproduce this issue as well. I believe I'll have to add it to the podspec and the xcodeproj.

**Comment by dmauro** [comment]
Importing into my framework via Carthage (`github "lyft/mapper" ~> 1.0.2`) and then linking it in the project. Nothing out of the ordinary. Then in my example project (which has my framework proj directly embedded) I see the warning when building, and when I run `carthage update --no-use-binaries` in my app (that's using my framework that's using Mapper) I see the warning there too.

**Comment by dmauro** [comment]
I didn't submit a PR just because I didn't know if there was a way to set it via xcconfig or something that you would prefer.

**Comment by keith** [comment]
Thanks! No worries, working on this now.

**Comment by keith** [comment]
Submitted https://github.com/lyft/mapper/pull/29 to fix this. I'll merge and create a new release (1.0.3) once it's green.

**Comment by keith** [comment]
Alright, 1.0.3 is up now. Feel free to reopen if you see any other issues! Thanks for reporting this!
