### ISSUE TITLE
More descriptive MapperError

### ISSUE THREAD

**Issue by litso** [lyft/mapper#31]
Understand that my implementation of `Mappable` init can throw any error I want, but was just seeing how receptive you would be to change along the following lines:

Would be nice to have an indication of which field caused the throw, possibly also an indication of why it was thrown. This would be a good way to get slightly more descriptive errors without having to implement custom throws from each call to `mapper.from`.

This change would potentially involve adding an associated message value to MapperError, something along the lines of:

```
public struct MapperError: ErrorType {
    case MapError(string)
    @warn_unused_result
    public init(message: String) {
       self = .MapError(message)
   }
}
```

**Comment by keith** [comment]
I'm totally open to this! We planned to do this originally but found that in our testing it didn't end up being a huge problem. I think ideally we could build this error pretty dynamically, having different cases for the key not existing in the JSON and it not being of the correct type etc. This also means we could generate the message easily since we have the expected type and the field name already.

**Comment by alliannas** [comment]
Something like this would be appreciated, at least for debug builds! :)

**Comment by keith** [comment]
Right now I'm finishing up https://github.com/lyft/mapper/pull/7 but after that I'll start working on this!

**Comment by tomaskraina** [comment]
Hey @keith, any progress with this one? I started using mapper recently and it would be super helpful to have more descriptive errors!

**Comment by jhihguan** [comment]
Hi @keith how's the progress? I'm a little depressive when the Error doesn't show more detail about what's the field it is or something related to it

**Comment by keith** [comment]
I've merged https://github.com/lyft/mapper/pull/48 which updates `MapperError` to be an enum with a few specific values rather than a struct. Thanks everyone!

**Comment by keith** [comment]
I'll make a release with these changes soon

**Comment by keith** [comment]
I've just pushed 2.1.0 which includes these changes!
