### ISSUE TITLE
Idea: Typed transformations and conversions

### ISSUE THREAD

**Issue by keith** [lyft/mapper#33]
Right now for transformations we do something like this:

``` swift
func someTransform<T>(object: AnyObject?) -> T {
    return ...
}
```

I wonder if we could come up with an interface that changed our transforms to looking like this:

``` swift
func someTransform<T, U: Convertible>(object: U) -> T {
    return ...
}
```

The benefit of this would be that right now for many transformations (and conversions), the first step is converting the `AnyObject?` to the actual JSON typed value. For example:

``` swift
extension NSURL: Convertible {
   static func fromMap(value: AnyObject?) throws -> NSURL {
        if let string = value as? String, let URL = NSURL(string: string) {
            return URL
        }

        throw MapperError()
    }
}
```

The first step here is getting a string, and then using that to create a URL.

I think it could be nice for us to create an interface that allowed functions to have the more specialized type, and reduced some of the mapper duplication. Depending on how we did this, it could also serve for even more complex transformations:

``` swift
func someTransform(objects: [Place]) -> [Place]) {
    return objects.map { $0.doSomething() }
}
```

Where right now this would be much more difficult.

I'd love to hear other's thoughts about this!

**Comment by Reflejo** [comment]
Big fan of this idea. We'll need to handle sequence types in a different way though, similar to what we are doing with other `Convertible`s

**Comment by keith** [comment]
We would probably get compile time safety for this for "free" since `Array` isn't `Convertible` and `U` would be required to be.

But yes we could definitely handle that too. I do wonder if we'd also still need to allow the `AnyObject` variation of this too.

**Comment by Reflejo** [comment]
Right, except that we have two different signatures, one that takes `U: Convertible, .. (U)` and another one that takes `U: Convertible, ... ([U])`.

**Comment by keith** [comment]
I'm still open to supporting this, but I don't have any plans to add it. Contributions welcome.
