### ISSUE TITLE
Hold JSON as AnyObject in Mapper

### ISSUE THREAD

**Issue by mrubin** [lyft/mapper#42]
Would you consider having `Mapper` hold `JSON` as an `AnyObject`?

All my server responses are wrapped in a 'data' field, like so:

```json
{
    "data" : [
      {
        "username" : "user_a"
      },
      {
        "username" : "user_b"
      }
    ]
}
```

I then want to directly create an array of `User` (see below) from my response. Since I don't have an outer object (like `Group` in your example) that would have an array of this type, I created a static function like so:

```swift
struct User: Mappable {
  let username: String

  init(map: Mapper) throws {
      try username = map.from("username")
  }

  static func createFromServerData(data: [String: AnyObject]) -> Result<[User]> {
      do {
          return .Success(try Mapper(JSON: data).from("data"))
      } catch {
          return .Failure(.InvalidResponse)
      }
  }
}
```

However, I don't want to repeat `"data"` all over the place, so I would like to extract it at the network level. The problem is that for the above JSON, this would give me an array.. but Mapper wants to store it as a dictionary.  When I use the

```swift
public func from<T: Mappable>(field: String) throws -> [T]
```

form like so:

```swift
try Mapper(JSON: data).from("")
```

the value returned from `JSONFromField()` would correctly be my array in an `AnyObject` and then it would be cast to an array of dictionaries... which would all work as expected.

If you were to implement this change, The wrinkle would be that in `JSONFromField()`, you would need to try to cast `self.JSON` as a dictionary (in order to call valueForKeyPath)?

What do you think?

Thank you.

**Comment by keith** [comment]
Thanks for the feedback @mrubin 

So I guess the bigger request here is having Mapper support arrays as a first class concern. Like you alluded to here:

> the value returned from JSONFromField() would correctly be my array in an AnyObject and then it would be cast to an array of dictionaries... which would all work as expected.

This would mean Mapper would have to take on handling dictionarys vs arrays. We've chosen, up to this point, not to have Mapper do this.

There are 2 ways you can work around this.

The first is what we do in our app. Somewhere in our network layer we have a callback like this:

```swift
... { response, _ in // response is a `NSDictionary?`
    let usersObject = response?["data"] as? NSArray
    let users = usersObject.map(User.from)
```

Here this uses [this initializer](https://github.com/lyft/mapper/blob/c69d8f2c3d96852a9a4beace153956971688b5c3/Sources/Mappable.swift#L57-L64) which accepts an `NSArray` and returns `[Self]?`.

The other very similar option would be to do this manually, similarly to how the above initializer is implement. Which would look something like this:

```swift
... { response, _ in // response is a `NSDictionary?`
    let usersObject = response?["data"] as? [NSDictionary] ?? []
    let users = usersObject.map(User.from)
```

This time the `User.from` initializer being called would be [this one](https://github.com/lyft/mapper/blob/c69d8f2c3d96852a9a4beace153956971688b5c3/Sources/Mappable.swift#L52-L55) but this would still end up creating a `[Self?]` array which you could then `flatMap`.


Would either of these solutions work for you?

**Comment by mrubin** [comment]
Thanks for the quick response! The first option seems to work well with my codebase - I'll have to do further testing. (I understand what you're getting at with the raw JSON server response being a dictionary - I just didn't see the protocol extension methods, I was only looking at Mapper.init).

```swift
struct User: Mappable {
  let username: String

  init(map: Mapper) throws {
      try username = map.from("username")
  }

  static func createFromServerData(data: [AnyObject]) -> Result<[User]> {
      guard let users = User.from(data) else {
          return .Failure(.InvalidResponse)
      }

      return .Success(users)
  }
}
```

It's a bit unfortunate to now have the mix of exceptions and optionals here.. but that's nitpicking territory :)

**Comment by keith** [comment]
I'm glad that should work! Feel free to reopen this if it doesn't!

On the exceptions vs optionals difference: the reason we chose to throw from initializers is because it makes handling the error cases much nicer. For example what you have now:

```swift
  init(map: Mapper) throws {
      try username = map.from("username")
  }
```

If we wanted to do an initializer that failed with optionals instead we'd end up with:

```swift
  init?(map: Mapper) {
      if let username: String = map.from("username") {
           self.username = username
      } else {
           return nil
      }
  }
```

Which is obviously much more verbose.

The reason our extensions end up converting it to optionals is just because we haven't fleshed out useful errors from mapper. In theory we could differentiate what we're throwing based on whether it was a missing key, or the wrong type etc. But up to this point we haven't done that. Because of that we felt like it's easier to deal with optionals instead. Of course if you wanted you could take the protocol extension you're now using and change it to this:

```swift
    @warn_unused_result
    public static func from(JSON: NSArray) throws -> [Self] {
        if let array = JSON as? [NSDictionary] {
            return try array.map { try self.init(map: Mapper(JSON: $0)) }
        }

        throw MapperError()
    }
```

Which would give you the same version, but using the do/try/catch error handling instead. Another reason we haven't opted to do this yet is that often we except you would just want to use `try?` with this, meaning it might as well return an optional. But that's just our personal preference.
