### ISSUE TITLE
Add 'update' method

### ISSUE THREAD

**Issue by adamastern** [lyft/mapper#43]
Is there any interest in adding an optional instance method to the Mappable protocol that allows a model to be updated post-creation. Similarly to the init(Mapper) initializer, this function would accept a mapper object, and give the model an opportunity to update any mutable properties. Happy to have a go at adding this...

**Comment by keith** [comment]
Up to this point we've thought immutable properties as a huge advantage of using mapper. The other problem with this plan is the limitation on optional protocol methods. We definitely don't want to require Mappable types to be limited to those inheriting from NSObject, or in general touching the Objective-C runtime. Unless we had some very compelling reasons to add this I would prefer this be an extension/new protocol specific to your use case.

**Comment by keith** [comment]
As another thought on this. If you'd like that functionality where the majority of your properties will end up as `var`, you could implement a library that worked that way with a protocol that looked something like this:

```swift
protocol Mappable {
    init()
    func map(map: Mapper)
}
```

Then you could always use this `map` function to "fill" your objects. Before we switched to this library our internal library actually did that. I did a talk on mapper where I showed some examples of what that looked like if you're interested: https://realm.io/news/slug-keith-smiley-embrace-immutability/
