### ISSUE TITLE
Nested enum doesn't work

### ISSUE THREAD

**Issue by dongyuan** [lyft/mapper#45]
see below unit test used for the case.

```
 func testArrayOfEnum() {
        struct Test: Mappable {
            let nests: [Nested]
            init(map: Mapper) throws {
                try self.nests = map.from("nests")
            }
        }
        
        enum Nested:String {
            case SAMPLE1 = "SAMPLE1"
            case SAMPLE2 = "SAMPLE2"
        }
        
        let test = try! Test(map: Mapper(JSON: ["nests": ["SAMPLE1","SAMPLE2"]]))
        XCTAssertNil(test.nests)
    }

```

**Comment by keith** [comment]
Sorry about not responding earlier, I saw this but then forgot to follow up.

See https://github.com/lyft/mapper/pull/34 for details about this case.

**Comment by keith** [comment]
This is now implemented via https://github.com/lyft/mapper/pull/61 I'll be cutting a new release shortly.

Please open an issue if you have any problems with it!
