### ISSUE TITLE
Is inheritance possible?

### ISSUE THREAD

**Issue by hunaid-hassan-confiz** [lyft/mapper#50]
I was wondering if could subclass my models. Right now compiler throws an error about 
`protocol 'Mappable' requirement 'from' cannot be satisfied by a non-final class ('AdDetailModel') because it uses 'Self' in a non-parameter, non-result type position`

**Comment by keith** [comment]
This is interesting. What does your model hierarchy look like?

**Comment by keith** [comment]
Feel free to open this with more info!
