### ISSUE TITLE
null fields

### ISSUE THREAD

**Issue by osrl** [lyft/mapper#51]
Sorry, just a question. using `optionalFrom` throws Error when handling null fields. Shouldn't it return nil? Am I missing some point?

**Comment by keith** [comment]
It should return nil. Which error are you seeing? No `optionalFrom` function defines the ability to `throws` either https://github.com/lyft/mapper/blob/master/Sources/Mapper.swift#L52

**Comment by osrl** [comment]
Just throws `MapperError` and XCode stops at exception breakpoint. So I thought app was crashed but it didn't. Sorry it's my bad.

**Comment by keith** [comment]
Ah yep, the Swift Exception will happen for all `try` statements regardless of if they're handled. Glad you figured it out!
