### ISSUE TITLE
Preliminary support for Swift 3

### ISSUE THREAD

**Issue by kiliankoe** [lyft/mapper#57]
Would it be possible to maintain a swift 3.0 branch until the official release?

I just ran the Xcode 8 migrator over the codebase (and updated the project settings to enable the recommended whole module optimization as well while at it) and everything seems to build fine. 
I'm just getting a lot of `warn_unused_result` warnings (not sure if already there previously) and an error on a missing file MapperTests. `make test-iOS` also fails on `protocol 'Mappable' can only be used as a generic constraint because it has Self or associated type requirements` and I didn't want to get much further into the code atm. Also didn't want to submit a PR with those issues^^

**Comment by keith** [comment]
I'm totally up for supporting this, and probably even a `swift-2.3` branch if there need to be any changes there. I'll look into this now.

**Comment by keith** [comment]
I have created both the `swift-2.3` and `swift-3.0` branches which can be found here:

https://github.com/lyft/mapper/compare/swift-2.3
https://github.com/lyft/mapper/compare/swift-3.0

Until the public release of Xcode 8 with these 2 versions of Swift, you'll have to specify the branches manually in however you're managing dependencies. Let me know if you run into any issues on these branches! I will continue pushing to them over the next few releases!

**Comment by kiliankoe** [comment]
Awesome, thank you!
