### ISSUE TITLE
Get feedback on failed parsing

### ISSUE THREAD

**Issue by plivesey** [lyft/mapper#71]
I have a feature request, and I took a look at how to implement it and am struggling to find an idea:
- I want to know when something goes wrong parsing, even if it was able to create a model (and I want the model also). Currently, if an optional field fails, it fails completely silently.

Ideas:

The easiest way to do it as far as I can see is add some sort of failure closure to the Mapper object which is called whenever a failure occurs.

A better way would be to throw an error, but include the actual model as part of that error. I don't think this is possible in swift though? Is it possible to include `self` in the object which you throw? Maybe you could do a convenience init which calls the other init first, then checks if there was an error, then throws a new error? Not sure if that works though...

Anyway, the real question is: is this a feature you think fits in with Mapper? It should definitely be opt in so backwards compatible, but interested in your thoughts.

**Comment by Reflejo** [comment]
What version of mapper are you using? Mapper supports throwing errors when the conversions fail. The error you get contains the field. If you have a snippet with your use case we can help you change it. Check https://github.com/lyft/mapper/blob/master/Tests/Mapper/ErrorTests.swift for some examples

**Comment by plivesey** [comment]
These errors are discarded though if it hits an optional field right? So, if I have an optional string foo and give it: `["foo": 2]` the model creation will succeed with no error right?

I'd like to get at this error.

**Comment by Reflejo** [comment]
Ah got it; so you are proposing to have an optionalFrom that throws? 

As in: supporting fields that can be nil but would throw if the type is incorrect?

Right now you can get the error if you don't use optionals but of course you'd get an error if the type comes null as well

**Comment by plivesey** [comment]
Yeah, or for something like this:
```
class Message {
    let sender: User?
}
class User {
    let username: String
}
```
Get the error if username is null. Currently, I think it'll ignore it and just set sender to nil? So distinguish between: user is missing and user failed to parse.

Anyway, this could be solved by just rethrowing everything, but I also would like the 'partial model'. Which is tough to do currently. That's why I was thinking of an error closure or something.

Does that make sense?

**Comment by dchohfi** [comment]
👍 any idea on this?

**Comment by i-schuetz** [comment]
Is it possible to get more context on the error? E.g. the complete json object (or maybe just an arbitrary message), sometimes the field content / throws cause is not enough to figure out where it is.

**Comment by keith** [comment]
> So distinguish between: user is missing and user failed to parse.

I'd be open to specific ideas about the design of this, but I'm not excited about the possibility of adding yet another function in the matrix of types (Convertible, Mappable, RawRepresentable) to decoding strategies (`try from`, `optionalFrom` and this new one) in our interface. If you have some ideas on how we could implement this with relative low overhead, I'm open to it. If so please file an new issue or submit an example in a PR.

> Is it possible to get more context on the error? E.g. the complete json object (or maybe just an arbitrary message), sometimes the field content / throws cause is not enough to figure out where it is.

There isn't a way to do this. I would suggest catching the error that is thrown from the model, and throwing a new error of your own with the added information you want. For example:

```swift
do {
    let user = try User(map: Mapper(json: dictionary))
    ...
} catch let error as MapperError {
    throw MyError.customError(error.whateverInfo, dictionary)
}
```
