### ISSUE TITLE
Deserialization of nested dictionaries

### ISSUE THREAD

**Issue by jerrygdm** [lyft/mapper#72]
Can you have a check on this: http://stackoverflow.com/questions/39124648/deserialization-with-modelmapper-on-dictionaries

Thanks so much!

**Comment by keith** [comment]
Hey @jerrygdm. You have 2 simple options here. You can either make a nested object:

```swift
struct Foo: Mappable {
    let bar: Bar

    init(map: Mapper) throws {
        bar = try map.from("bar")    
    }
}

struct Bar: Mappable {
    let something: String

    init(map: Mapper) throws {
        something = try map.from("something")
    }
}
```

Which would correctly handle JSON like this:

```json
{
    "bar": {
        "something": "hi"
    }
}
```

Or you can use `.` in your JSON key to make it a nested key path. For the same JSON you could do this instead:

```swift
struct Foo: Mappable {
    let something: String

    init(map: Mapper) throws {
        something = try map.from("bar.something")    
    }
}
```

Let me know if that doesn't work for your case!

**Comment by jerrygdm** [comment]
Thanks so much...I prefere the first, maybe is most reusable :)
