### ISSUE TITLE
Compile Errors on 4.0.0 for Swift v3

### ISSUE THREAD

**Issue by devdebonair** [lyft/mapper#74]
Is anyone else getting syntax errors for v4.0.0?

**Comment by sberrevoets** [comment]
Hey @devdebonair, 4.0.0 is a Swift 2.3 release so it's not surprising this doesn't build yet for Swift 3. We will create another major release for Swift 3 soon.

See https://github.com/lyft/mapper/pull/73 for some more details.

**Comment by devdebonair** [comment]
Ok. I should've taken a deeper read.

**Comment by sberrevoets** [comment]
In the meantime, since the Swift 3 branch wasn't building anymore, here's a PR/branch that once merged will make it build again: https://github.com/lyft/mapper/pull/75.

**Comment by keith** [comment]
Please follow along at https://github.com/lyft/mapper/pull/76 now for Swift 3.0 compat!

**Comment by Killectro** [comment]
Not sure if I should comment here or on #76 but is there any ETA on when this will land in Cocoapods @keith? I'm using it in a podspec so I'm unable to point to a specific branch.

**Comment by sberrevoets** [comment]
We are holding off from releasing an update on CocoaPods right now to give dependencies some more time to migrate their codebases from Swift 2.3 to Swift 3. I did just push a `5.0.0` tag that can be used in podspecs to specify the Swift 3 version of the library.

Let me know if you're running into problems!

**Comment by juliengdt** [comment]
@sberrevoets little prob on Swift 3 branch: s.version on podspec is still 4.0.0 :)

**Comment by sberrevoets** [comment]
Thanks, updated now to be 5.0.0-beta.2.

**Comment by keith** [comment]
I've pushed 5.0.0 with Swift 3 support to CocoaPods! Please open new issues for any problems you have! Thanks everyone!
