### ISSUE TITLE
[Question] Beta tag for podspec use

### ISSUE THREAD

**Issue by juliengdt** [lyft/mapper#77]
Hi, 

I'm currently using mapper as a dependency in another pod.
This parent pod is merging to Swift 3.0

Could it be possible to ```pod repo push``` a tag like ```5.0.0-beta``` and use it for ```swift-3.0``` branch ?
That will help a lot for Swift 3.0 merging session. 

Happy coding

Cheers From France

**Comment by sberrevoets** [comment]
Hey @juliengdt, thanks for bringing this up! I've just pushed a `5.0.0-beta` tag that can be used in pod specs. Let me know if you're running into problems!

**Comment by juliengdt** [comment]
Hello,

Thanks a lot !!
