### ISSUE TITLE
Map Dictionary to [Self]?

### ISSUE THREAD

**Issue by mergesort** [lyft/mapper#79]
I was discussing with @sberrevoets elsewhere, and other JSON libraries have functionality that allows you to return an array of Mappables, rather than just one.

I have a convert function, using a generic that takes vends a `T`, but I can’t make it take in `[T]`, because `[T]` is not Mappable, even though `T` technically is. This would be useful because instead of having to create an intermediate object (like `TList`) around your Mappable type with one field (`[T]`), you'd be able to just vend a `[T]` from the JSON response.

Currently these two functions exist.

```
static func from(_ JSON: NSDictionary) -> Self?

static func from(_ JSON: NSArray) -> [Self]?
```

And I'd propose a third to one be added.

```
static func from(_ JSON: NSDictionary) -> [Self]?
```

Thanks a lot! Happy to add on any more information to help.

**Comment by keith** [comment]
Interesting. As an aside, I would love to also make `[T]` `Mappable` but until you can do something like `extension Array where Element: Mappable` we're SOL there.

But how would this new function work? Right now I'm not sure how we can infer a single solution for all users of how you go from a dictionary to an array of elements.

In our case at Lyft we often have JSON that looks like this:

```json
{
  "things": [
     { ... },
     { ... }
  ]
}
```

And we'll often decode this to `[Thing]` by, in our API callback, doing:

```swift
let response: NSDictionary = ...
let things = response["things"].flatMap(Thing.init)
```

But that in between step of pulling the array out via a string key is the part that I'm not seeing yet.

**Comment by mergesort** [comment]
@keith Why can't you do `extension Array where Element: Mappable`? I just whipped this up and it worked fine.

```
protocol Foo {

}

extension Array where Element: Foo {

    func doSomething() {
        print("X")
    }

}

func parseFoo<F>(foo: F) where F: Foo {

    [foo].doSomething()

}```

This sounds like a really good solution to me, I hadn't considered mapping the response onto an array. Now that I've stepped back and thought about it some more, that's the solution I'd actually want Mapper to provide as well, where a key is provided into the function and an array is vended.

Does that sound like functionality you think should be a part of Mapper, or something that's external users should write?

**Comment by sberrevoets** [comment]
> But that in between step of pulling the array out via a string key is the part that I'm not seeing yet.

I had this same question. If you're providing a key anyway (which I think you'd have to), then you might as well read that straight from the dictionary and use the existing `NSDictionary -> [Self]?` method right?

**Comment by mergesort** [comment]
Yes, that's a valid point, and I agree with both of your thoughts on the matter. I'll leave this open so @keith can comment on the `extension Array where Element: Mappable` statement [above](https://github.com/lyft/mapper/issues/79#issuecomment-249371774).

**Comment by keith** [comment]
Sorry what I meant is that it would be awesome if we could do:

```swift
extension Array: Mappable where Element: Mappable {
```

But we can't have a conditional conformance here. We could add custom methods to Array based on the elements, but I'd really just like to be able to hook into the existing protocol with a conditional conformance. As of this week there's a [proposal for this](https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20160926/027300.html)

**Comment by mergesort** [comment]
Ah, gotcha. That makes more sense. Let's hope for the best... goooo proposal! 🎉

**Comment by mergesort** [comment]
Just wanted to chime back in and say I believe this is possible now as of Swift 3.1. 🙂

**Comment by keith** [comment]
I will investigate this soon!

**Comment by keith** [comment]
Apparently I won't. If someone wants to pick this up feel free to submit a PR!
