### ISSUE TITLE
Pod install unable to find specification

### ISSUE THREAD

**Issue by corywilhite** [lyft/mapper#9]
using `pod 'ModelMapper'`, during pod install, the install fails with the following error:

`[!] Unable to find a specification for 'ModelMapper'`

I tried pod install, pod update, and a clean pod install and they all failed to find the spec

**Comment by Reflejo** [comment]
What `source` are you using in your `Podfile`?. I'd try removing the specs repo as

```bash
$ sudo rm -fr ~/.cocoapods/repos/master
$ pod setup
```

**Comment by corywilhite** [comment]
Ah shoot good call, I had it setup to use the CocoaPods/Specs.git source but it wasn't getting updated. 

clearing it out did the trick.
