### ISSUE TITLE
Additional parameters when creating object with map.from("key")

### ISSUE THREAD

**Issue by darrarski** [lyft/mapper#93]
Having a JSON:
```JSON
{"name": "John"}
```
and a model:
```swift
struct User {
    let name: String
}
```
I implemented `Mappable` protocol in extension to `User` struct, so I can create my user models from JSON:
```swift
extension User: Mappable {
    init(map: Mapper) throws {
        name = try map.from("name")
    }
}
```
I would like to add additional property to `User` struct:
```swift
struct User {
    let name: String
    let age: Int
}
```
The value of that property doesn't come from JSON, I would like to provide it manually. Unfortunately, I can't add it to `init(map: Mappable)` initializator, as it will brake conformance to `Mappable` protocol. 

Does mapper allows to add custom parameters to object when parsing JSONs?

I would like to be able to write code like this:
```swift
let map = Mapper(JSON: ...) // {"name": "John"}
let user: User = User(map: map, age: 33)
```
and:
```swift
let map = Mapper(JSON: ...) // {"user": {"name": "John"}}
let user: User = try map.from("user", age: 33)
```
which of course will require implementing custom `from` function for `Mapper`, but I am not sure how to do it or if it's even possible.

**Comment by sberrevoets** [comment]
Currently that's not possible with a pure mapper implementation. We have a few cases in our app where we need the same, and in those cases we have chosen to not make that particular model `Mappable` but instead create our initializer. That looks something like this:

```swift
struct User {
    let userID: String
    let firstName: String
    let lastName: String

    init(map: Mapper, userID: String) throws {
        self.userID = userID

        self.firstName = try map.from("firstName")
        self.lastName  = try map.from("lastName")
    }
}
```

**Comment by keith** [comment]
The missing part from your example is something like this:

```swift
let userDictionary: NSDictionary = try map.from("user")
let user = User(map: Mapper(JSON: userDictionary), age: 33)
```

Another thing that we've done a few times is pass a curried transformation function to sub-models, in the case we actually need to share parsing logic.

**Comment by tamoyal** [comment]
How would you then handle a parent model trying to instantiate the `User` object (I'm using classes)? Let's say I had a `Team` that had a bunch of users.

```
struct Team {
    let users: [User]?
    let name: String

    init(map: Mapper, name: String) throws {
        self.name = name
        self.users = map.optionalFrom("users") // doesn't work
    }
}
```

**Comment by keith** [comment]
You could use a similar snippet to my example above, but map the users key directly to an array of NSDictionaries first

**Comment by keith** [comment]
Feel free to submit a new issue if this is still a problem!
