### ISSUE TITLE
How to map and change to different type?

### ISSUE THREAD

**Issue by rlam3** [lyft/mapper#95]
How to map and change to different type?
I would like to map a string to an int. is there anyway for me to do it within the initalizer? Thanks!

**Comment by keith** [comment]
There are a few ways you could do this.

If this is just a one off case in your code you could simply do something like this:

```swift
let temp: String = try map.from("key")
self.intProperty = Int(temp)
```

If this is something that's extremely standard for your case you could define a simple transformation function like this:

```swift
extension Transform {
    func stringToInt(object: Any) throws -> Int {
        guard let string = object as? String else {
            throw .convertibleError(value: object, type: String.self)
        }

        return Int(string)
    }
}
```

And then use it like this:

```swift
self.intProperty = try map.from("key", transformation: Transform.stringToInt)
```

Let me know if you have any other questions!

**Comment by rlam3** [comment]
@keith Thanks for the pointer. 

However Following your extension way of doing this. I'm getting the following error:



```swift
 Cannot convert value of type '(Transform) -> (Any) throws -> Int' to expected argument type '(Any) -> _'
```
on the follwing line
```swift
self.intProperty = try map.from("key", transformation: Transform.stringToInt)
```

**Comment by keith** [comment]
Edited, it should be static. But really that's just an example, you'll have to write your own for your own case.
